#!/bin/bash
echo "Testing if vercel dev is working..."
echo ""
echo "1. Make sure you're in the web directory"
echo "2. Stop the current vercel dev (Ctrl+C)"
echo "3. Run: npm run dev:vercel"
echo ""
echo "You should see output like:"
echo "  > Ready! Available at http://localhost:3000"
echo ""
echo "If you see 'Running Dev Command \"vite\"' instead,"
echo "Vercel is not detecting the serverless functions."
echo ""
echo "The /api folder should be detected automatically."
echo "If not, check that:"
echo "  - Files are in web/api/*.ts"
echo "  - Files export default async function handler"
echo ""
